[package]
name = "clcicd"
version = "0.1.0"
authors = ["Jon Barker <jonathan.t.barker@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.26.0"
indicatif = "0.11.0"
console = "0.7.5"
reqwest = "0.9.15"
clokwerk = "0.1.0"
